/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*; //importing all sql package
import javax.swing.JOptionPane;
/**
 *
 * @author Josh
 *        
 *         
 */
public class login extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 492));
        setMinimumSize(new java.awt.Dimension(800, 492));
        setPreferredSize(new java.awt.Dimension(800, 492));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ONE PLAYER HANGMAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(207, 21, 435, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel2.setText("NEW PLAYER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(163, 115, 139, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setText("EXISTING PLAYER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(534, 115, 193, 26);

        tf1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf1.setText("Enter nickname to play");
        getContentPane().add(tf1);
        tf1.setBounds(534, 153, 210, 48);

        user.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        user.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(163, 153, 202, 48);

        Name.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(Name);
        Name.setBounds(163, 213, 202, 49);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("NEW GAME");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 210, 150, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 290, 110, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 380, 120, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel4.setText("Nickname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 163, 104, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(38, 223, 61, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel6.setText("Nickname");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(412, 163, 104, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 580, 270);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 260, 340, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 0, 290, 270);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 220, 340, 240);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 250, 350, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Variables to get texk from the textfield and to update in the data base
String nickname = user.getText();
String name = Name.getText();
int win = 0;
int loose = 0;
int draw = 0;


try{
     Class.forName("java.sql.Driver"); 
     con = DriverManager.getConnection("jdbc:mysql:///hangman","root","");
     stmt = con.createStatement();
      String query = "Insert into players values('" + nickname + "','" + name + "','" +win + "','" +loose+ "','" + draw +"');";  // db query to inserr to database
     stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(null," Welcome New Player ! \n\n Please Enter Your Nickname \nOn the  [ Existing Player ]  Field \n\n To Play Game ");
     
     
   }
catch(Exception e){
     JOptionPane.showMessageDialog(null,"Player with thesame Nickname Exist ! \n\nPls try a different Nickname");    
                  }

      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String user = tf1.getText();
     try {
    Class.forName("java.sql.Driver");
    con = DriverManager.getConnection("jdbc:mysql:///hangman","root","");
    stmt = con.createStatement();
    String query = "Select * from players Where nickname = '" + user + "';"; // Query to locate player in the database (for login)
    
   rs = stmt.executeQuery(query);
    if (rs.next()){
      
  
//  JOptionPane.showMessageDialog(null,"Login Successful");  //to coss-check

    
    hangman x = new hangman();
       hangman.jTextField1.setText(login.tf1.getText()); 
       // This transfer the data from the user input and send it to the Label on the Game Session in hangman Jframe
      //to show the player in session and also enable to keep record for the particular player
       x.setVisible(true); 
       close();
                   
                  } 
    else 
        JOptionPane.showMessageDialog(null,"Incorrect Nickname or Player does not Exist !");
    rs.close();
    stmt.close();
    con.close();
     }    
catch (Exception e){
    JOptionPane.showMessageDialog(null,"Error in connectivity");
    }
    
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // To set Textfield empty whenever mouse is click on this screen
          tf1.setText("");
          user.setText("");
          Name.setText("");
    }//GEN-LAST:event_formMouseClicked
    /**
     * @param args the command line arguments
     */
    private void close(){        //close and dispose method for frames
        this.setVisible(false);
        this.dispose();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField Name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField tf1;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    
}
