/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Josh
 *       
 *       
 */
public class YouLoose extends javax.swing.JFrame {

    /**
     * Creates new form YouLoose
     */
    public YouLoose() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mt = new javax.swing.JLabel();
        rt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(490, 694));
        setMinimumSize(new java.awt.Dimension(490, 694));
        setPreferredSize(new java.awt.Dimension(490, 694));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText(" Sorry !!    You Loose  !!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(122, 10, 247, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("You could not Save the man from Hanging");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 59, 437, 29);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 600, 150, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 600, 110, 50);

        jPanel1.setMaximumSize(new java.awt.Dimension(449, 449));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hangman8.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(21, 99, 414, 446);

        mt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mt.setText("The correct word was ");
        getContentPane().add(mt);
        mt.setBounds(20, 560, 199, 22);

        rt.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        rt.setText("x      x      x      x");
        getContentPane().add(rt);
        rt.setBounds(230, 550, 218, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 0, 150, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 0, 180, 210);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 200, 110, 210);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 400, 110, 210);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 510, 110, 160);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 520, 110, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 510, 110, 160);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 520, 110, 160);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-10, 520, 110, 160);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 370, 60, 160);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 220, 60, 160);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 70, 60, 160);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 150, 110);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        hangman x = new hangman();
       hangman.jTextField1.setText(login.tf1.getText());
      // Enable the player to remain in the game session
       x.setVisible(true);
       close();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
 public void setLabelText(String text) {
        rt.setText(text);      // Setting the hiddenWord to the appropriate label
        
    }
 
  private void close() {
        this.setVisible(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouLoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouLoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouLoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouLoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouLoose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mt;
    private javax.swing.JLabel rt;
    // End of variables declaration//GEN-END:variables

   

   
}
