/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Josh
 *       
 *        
 */
public class YouWin extends javax.swing.JFrame {

    /**
     * Creates new form YouWin
     */
    public YouWin() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 655));
        setMinimumSize(new java.awt.Dimension(540, 655));
        setPreferredSize(new java.awt.Dimension(540, 655));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 560, 150, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel2.setText("Congratulations !!  You Win !!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(73, 8, 360, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hangman0.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(48, 107, 440, 440);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("You have save the man from Hanging  !!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 70, 414, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 500, 190, 130);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(369, 559, 120, 48);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 230, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 0, 230, 150);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 0, 230, 150);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 130, 100, 150);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 260, 100, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-10, 530, 100, 100);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(370, 500, 190, 130);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 500, 190, 130);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(470, 400, 100, 150);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, 130, 100, 150);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-10, 270, 100, 150);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Han2_1.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(-10, 410, 100, 150);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     hangman x = new hangman();
       hangman.jTextField1.setText(login.tf1.getText()); //Enable the player to remain in game session
       x.setVisible(true);
       close();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
 private void close() {          //close and dispose method for frames
        this.setVisible(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
